# Generated by Django 2.2.12 on 2020-04-19 21:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileId', models.CharField(blank=True, default=uuid.uuid4, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.TextField()),
                ('lastName', models.TextField()),
                ('password', models.CharField(max_length=100)),
                ('productAmount', models.IntegerField(blank=True, null=True)),
                ('rentedProductAmount', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
