# Generated by Django 2.2.12 on 2020-04-19 22:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerId', models.CharField(blank=True, default=uuid.uuid4, max_length=100, null=True)),
                ('replyEntryDate', models.DateTimeField()),
                ('replyContent', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(blank=True, default=uuid.uuid4, max_length=100, null=True)),
                ('orderStartDate', models.DateTimeField()),
                ('orderEndDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductId', models.CharField(blank=True, default=uuid.uuid4, max_length=100, null=True)),
                ('productType', models.TextField(blank=True, null=True)),
                ('productName', models.TextField()),
                ('productVerification', models.BooleanField(default=False)),
                ('productLicense', models.TextField(blank=True, null=True)),
                ('createDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileId', models.CharField(blank=True, default=uuid.uuid4, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.TextField()),
                ('lastName', models.TextField()),
                ('password', models.CharField(max_length=100)),
                ('productAmount', models.IntegerField(blank=True, null=True)),
                ('rentedProductAmount', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionId', models.CharField(blank=True, default=uuid.uuid4, max_length=100, null=True)),
                ('questionEntryDate', models.DateTimeField()),
                ('questionContent', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
