# Generated by Django 2.2.12 on 2020-04-21 18:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_userprofileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profileId',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, null=True),
        ),
    ]
