# Generated by Django 2.2.12 on 2020-04-22 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_profile_profileid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
