# Generated by Django 3.0.5 on 2020-04-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='rentPricePerDay',
            field=models.IntegerField(null=True),
        ),
    ]
