# Generated by Django 2.2.12 on 2020-04-19 21:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(blank=True, default=uuid.uuid4, max_length=100, null=True)),
                ('orderStartDate', models.DateTimeField()),
                ('orderEndDate', models.DateTimeField()),
            ],
        ),
    ]
