# Generated by Django 2.2.12 on 2020-04-19 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductId', models.CharField(blank=True, default=uuid.uuid4, max_length=100, null=True)),
                ('productType', models.TextField(blank=True, null=True)),
                ('productName', models.TextField()),
                ('productVerification', models.BooleanField(default=False)),
                ('productLicense', models.TextField(blank=True, null=True)),
                ('createDate', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
